### ISSUE TITLE
Development environment setup

### ISSUE THREAD

**Issue by rupendra1817** [IntelLedger/sawtooth-dev-tools#3]
I want to setup development environment for sawtooth lake project. 
I want to know given below details to setup development environment-
1- Operating system
2- IDE name
3- Dependencies if any

If any one have development environment setup guide then kindly share it.

**Comment by jsmitchell** [comment]
Hi Rupendra,

Please take a look at the [tutorial](http://intelledger.github.io/tutorial.html) which includes developer environment setup. Let me know if you have any questions.

**Comment by rupendra1817** [comment]
Hi jsmitchell,

Refereed tutorial contains process of setting virtual development environment for testing MarketPlace Transaction Family.
I want to setup actual development environment. And want to create new Transaction Family. 

How developer develop code by using vagrant ssh.
I am little bit confused. According to me there is requirement of IDE to develop application.

Please suggest me right way to start development.

**Comment by jsmitchell** [comment]
We use the provided vagrant environment as our actual development environment. It ensures consistency amongst developers.

Since all of the code repositories are shared with the host OS, you can edit your code on the host if you like. We don't specify any sort of IDE. You are free to use what you wish.

PyCharm includes support for hooking into a remote interpreter instance (including inside vagrant). See https://blog.jetbrains.com/pycharm/2013/03/how-pycharm-helps-you-with-remote-development/

Good luck!

**Comment by jsmitchell** [comment]
Also, there are some clues to get you started on writing your own Transaction Family at the end of this page: http://intelledger.github.io/sawtooth_developers_guide/architecture_overview.html

Take a look at the implementation of IntegerKeyRegistry in sawtooth-core for a simple Transaction Family example.

**Comment by rupendra1817** [comment]
Kindly tell me 'Sawtooth lake' is private or public blockchain.

**Comment by jsmitchell** [comment]
Hi rupendra, Sawtooth Lake is a platform for developing distributed ledgers via construction of new Transaction Families. There is nothing about it that prescribes either public or private usage.

I am going to close this issue out as I assume the original question has been addressed.

Thanks,

James
